
# PERSONALIZATION
# Site variables
name: Catalan Club University Colorado
# og: assets/img/og.png
logo: assets/img/logo.png
# original_repo: https://github.com/hackcu/events
description: CU Catalan Club aims to share Catalan culture, gastronomy, history and politics at the University of Colorado Boulder.
# ga: UA-109088240-1
domain: cucat.github.io/landing/


# Style variables
accent_color: "#FF5252"
events_overlay_color: "#FBC02D"
background_color: "#FAFAFA"
footer_text_color: "#666666"
events_bg_img: assets/img/people.png

# START THEME 2
# accent_color: "#AA401B"
# events_overlay_color: "#225E50"
# END THEME 2

# START THEME 3
# accent_color: "#FF5722"
# events_overlay_color: "#2697FF"
# END THEME 3

# START THEME 4
# accent_color: "#FF5252"
# events_overlay_color: "#2697FF"
# END THEME 4

# START WINTER THEME
# accent_color: "#165E33" 
# events_overlay_color: "#AA504A"
# END WINTER THEME

# Author variables
author: Catalan Club University Colorado
author-description: "CU Catalan Club aims to share Catalan culture, gastronomy, history and politics at the University of Colorado Boulder. This club is a non-profit organization intended to serve as an exchange platform between American and Catalan cultures, and a means of encouraging Catalan students to socialize and share different viewpoints with American and other international students. This will be accomplished through several activities and cultural events throughout the year."
email: catalanclub@colorado.edu

# Social media + community variables
# twitter: hackcu
fb: cucatalanClub
# fb-community: cucatalanClub
# slack-signup: https://slack.hackcu.org
# instagram: hackcu
# github: hackcu



# TIMEZONE
# Needs to be string from: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: America/Denver
# Based on: http://erics-notes.blogspot.com/2013/05/fixing-ics-time-zone.html
ical_timezone: |-
  BEGIN:DAYLIGHT
  TZOFFSETFROM:-0700
  TZOFFSETTO:-0600
  TZNAME:MDT
  DTSTART:19700308T020000
  RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
  END:DAYLIGHT
  BEGIN:STANDARD
  TZOFFSETFROM:-0600
  TZOFFSETTO:-0700
  TZNAME:MST
  DTSTART:19701101T020000
  RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
  END:STANDARD
 
# Internal configuration
sass:
    sass_dir: assets/_sass
    style: compressed
